Umbraco Redesign/Models/BulletList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Umbraco_Redesign.Models
{
    public class BulletList
    {
        public int Id { get; set; }
        public string Contenturl { get; set; }
        public object IconName { get; set; }
        public string ListItemDescription { get; set; }
        public string Title { get; set; }
    }
}

Umbraco Redesign/Controllers/BoxLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web.Mvc;
using Umbraco_Redesign.Models;
using Umbraco.Web;
using HtmlAgilityPack;

namespace Umbraco_Redesign.Controllers
{
    public class BoxLayoutController : SurfaceController
    {
        // GET: BoxLayout
        public ActionResult Index(int? tabId)
        {
            if(Request.Params["tab"] != null && Request.Params["client"] != null && Request.Params["version"] != null)
            {
                var tab = Request.Params["tab"];
                var privateReporting = Umbraco.TypedContentAtRoot().FirstOrDefault().Descendants().Where(t => t.Name.ToLower()
                .Contains("summary") && t.Name.ToLower().Contains("reporting") && t.Name.ToLower().Contains("clients")).FirstOrDefault();

                if(privateReporting != null)
                {
                    tabId = privateReporting.Id;
                }

            }


            var tabNode = Umbraco.TypedContent(tabId);


            var boxes = GetBoxes(tabNode);

            if(boxes.Count() > 0)
            {
                return PartialView("boxLayout", boxes);
            }

            return CurrentUmbracoPage();
        }

        private List<Box> GetBoxes(IPublishedContent tabNode)
        {
            var boxes = new List<Box>();
            var pricingBoxes = tabNode.Descendants().Where(t => t.DocumentTypeAlias == "pricingBox").ToList();

            if (pricingBoxes.Count() == 0)
                return boxes;

            for (var tabCount = 0; tabCount < 3; tabCount++)
            {
                var tab = pricingBoxes[tabCount];


                //foreach (var tab in tabNode.Descendants().Where(t => t.DocumentTypeAlias=="pricingBox").ToList())
                //{

                    var boxOrderId = tab.GetPropertyValue<string>("pricingBoxNumber") != String.Empty ? tab.GetPropertyValue<string>("pricingBoxNumber"): String.Empty;
                    var themeColor = tab.GetPropertyValue<string>("pricingBoxThemeColorPicker");
                    var boxImage = tab.GetPropertyValue<string>("pricingBoxImage");
                    var imageUrl = Umbraco.TypedMedia(boxImage.ToString()) != null ? Umbraco.TypedMedia(boxImage.ToString()).Url : String.Empty;
                    var boxTitle = tab.GetPropertyValue<string>("pricingBoxTitleText");
                    var boxDescription = tab.GetPropertyValue<string>("pricingBoxDescription");
                    var features = tab.GetPropertyValue<string>("pricingBoxFeaturesList");
                    var tickBoxImage = tab.GetPropertyValue<string>("pricingBoxBulletListImage");
                    var listImage = "<li class='bulletListImage' style='list-style-type: square'>";
                    var tickBoxImageUrl = Umbraco.TypedMedia(tickBoxImage.ToString()) != null ? Umbraco.TypedMedia(tickBoxImage.ToString()).Url : String.Empty;
                    if (tickBoxImageUrl != String.Empty)
                    {
                        listImage = "<li class='bulletListImage' style='background-image: url(" + tickBoxImageUrl + ")'>";
                    }

                    features = features.Replace("<li>", listImage);
                    var boxSummaryText = tab.GetPropertyValue<string>("pricingBoxSummaryText");
                    var boxButtonText = tab.GetPropertyValue<string>("pricingBoxButtonText");
                    var enquiryButtonText = tab.GetPropertyValue<string>("pricingBoxButtonEnquiryType");

                    var optionIcons = tab.GetPropertyValue<IEnumerable<string>>("pricingBoxOptionIcons");
                    var selectedOptionIcons = new List<OptionIcon>();

                    foreach(var icon in optionIcons)
                    {
                        var optionalIcons = tabNode.Descendants().Where(tn => tn.DocumentTypeAlias == "optionIcons").FirstOrDefault();
                        var optionIconNode = optionalIcons != null? optionalIcons.Children().Where(t => t.Name.ToLower().Contains(icon.ToLower())).FirstOrDefault(): null;

                        if(optionIconNode != null)
                        {
                            var title = optionIconNode.GetPropertyValue<string>("iconExampleTitle");
                            var iconImage = Umbraco.TypedMedia(optionIconNode.GetPropertyValue("iconImage").ToString());
                            var leftBoxContent = Umbraco.TypedMedia(optionIconNode.GetPropertyValue("iconExampleContentLeftBox").ToString());
                            var leftBoxExampleLink = optionIconNode.GetPropertyValue<string>("iconExampleContentLeftLink");
                            var middleBoxContent = Umbraco.TypedMedia(optionIconNode.GetPropertyValue("iconExampleContentMiddleBox").ToString());
                            var middleBoxExampleLink = optionIconNode.GetPropertyValue<string>("iconExampleContentMiddleLink");
                            var rightBoxContent = Umbraco.TypedMedia(optionIconNode.GetPropertyValue("iconExampleContentRightBox").ToString());
                            var rightBoxExampleLink = optionIconNode.GetPropertyValue<string>("iconExampleContentRightLink");

                        var optionIcon = new OptionIcon
                        {
                                Id = Convert.ToInt32(optionIconNode.Id),
                                title = optionIconNode.GetPropertyValue<string>("iconExampleTitle"),
                                image = iconImage != null ? iconImage.Url : String.Empty,
                                leftBoxContent = leftBoxContent != null? leftBoxContent.Url: String.Empty,
                                leftExampleLink = leftBoxExampleLink,
                                middleBoxContent = middleBoxContent != null? middleBoxContent.Url: String.Empty,
                                middleExampleLink = middleBoxExampleLink,
                                rightBoxContent = rightBoxContent != null? rightBoxContent.Url: String.Empty,
                                rightExampleLink = rightBoxExampleLink
                            };

                            if(optionIcon != null)
                            {
                                selectedOptionIcons.Add(optionIcon);
                            }
                        }

                        
                    }

                    var box = new Box
                    {
                        Id = tabCount,
                        BoxOrderId = Convert.ToInt32(boxOrderId),
                        ThemeColor = themeColor,
                        ImageUrl = imageUrl,
                        Title = boxTitle,
                        DescriptionText = boxDescription,
                        Features = features,
                        BulletImageUrl = tickBoxImageUrl,
                        SummaryText = boxSummaryText,
                        buttonText = boxButtonText,
                        optionIcons = selectedOptionIcons,
                        EnquiryTypeButton = enquiryButtonText

                    };

                    if(box != null)
                    {
                        boxes.Add(box);
                    }


                    //var box = new Box
                    //{
                    //    BoxOrderId = Convert.ToInt32(tab.GetPropertyValue<int>("pricingBoxNumber")),
                    //    ThemeColor = tab.GetPropertyValue<string>("pricingBoxThemeColorPicker"),
                    //    ImageUrl = tab.GetPropertyValue<string>("")


                    //};

                    //if (box != null)
                    //{
                    //    boxes.Add(box);
                    //}
                    
                //}    
            }

            return boxes;
        }

        public ActionResult GetIconContent(string iconName, string boxNumber)
        {
            string boxName = String.Empty;

            switch (boxNumber)
            {
                case "1":
                    boxName = "Left";
                    break;
                case "2":
                    boxName = "Middle";
                    break;
                case "3":
                    boxName = "Right";
                    break;
            }

            var root = Umbraco.TypedContentAtRoot().First();
            var demoButtonOptions = root.Descendants().Select(x => x).Where(x => x.DocumentTypeAlias == "pricing").FirstOrDefault();
            string demoButtonText = String.Empty;

            if (demoButtonOptions != null)
            {
                demoButtonText = demoButtonOptions.GetPropertyValue<string>("demoRequestDemoText");
            }

            var iconContent = root.Descendants().Where(x => x.DocumentTypeAlias == "optionIcon" && x.Id.ToString() == iconName).FirstOrDefault();

            IPublishedContent icon = null;
            string iconUrl = String.Empty;
            string iconTitle = String.Empty;
            string iconType = String.Empty;

            if (iconContent != null)
            {
                var test = iconContent.GetPropertyValue<string>("IconExampleContent" + boxName + "Link");

                if (iconContent.GetPropertyValue<string>("IconExampleContent" + boxName + "Link") != String.Empty)
                {
                    //icon = (IPublishedContent)iconContent.GetPropertyValue("IconExampleContent" + boxName + "Link");
                    iconUrl = iconContent.GetPropertyValue<string>("IconExampleContent" + boxName + "Link");
                    iconType = "link";
                }
                else
                {
                    icon = Umbraco.TypedMedia(iconContent.GetPropertyValue("iconExampleContent" + boxName + "Box").ToString());
                    iconUrl = icon.Url;
                    iconType = icon.GetPropertyValue<string>("umbracoExtension");
                }

                if (icon != null || iconUrl != String.Empty)

Umbraco Redesign/Controllers/OfficesController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Core;
using Umbraco.Core.Models;
using Umbraco.Web;
using Umbraco.Web.Extensions;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;
using Umbraco_Redesign.Models;

namespace Umbraco_Redesign.Controllers
{
    public class OfficesController : SurfaceController
    {
        // GET: Offices
        public ActionResult Index(int nodeId)
        {
            var offices = GetOffices(nodeId);
            return PartialView("Office", offices);

        }
        public List<OfficesModel> GetOffices(int nodeId)
        {
            List<OfficesModel> OfficesList = new List<OfficesModel>();
            string officeFlag = String.Empty;
            string officeName = String.Empty;
            string officeAddressName = String.Empty;
            string officeAddressLine1 = String.Empty;
            string officeAddressLine2 = String.Empty;
            string officeAddressLine3 = String.Empty;
            string officeAddressLine4 = String.Empty;
            string officeTown = String.Empty;
            string officeCounty = String.Empty;
            string officePostcode = String.Empty;
            string officePhone = String.Empty;
            string extraPhone = String.Empty;
            string officeEmail = String.Empty;
            string extraHeading = String.Empty;
            string extraHeadingContent = String.Empty;
            string mobilePhone = String.Empty;
            string extraEmail = String.Empty;
            string officeWebsite = String.Empty;
            string officeCountryCode = String.Empty;
            string RegisteredAddressLine1 = String.Empty;
            string RegisteredAddressLine2 = String.Empty;
            string RegisteredAddressLine3 = String.Empty;
            string RegisteredTown = String.Empty;
            string RegisteredPostcode = String.Empty;
            string RegisteredPhone = String.Empty;
            string NumberOfValues = String.Empty;
            string orContactUs = String.Empty;
            string orPressOne = String.Empty;
            string findOutHow = String.Empty;

            IPublishedContent OfficesNode = Umbraco.TypedContentAtRoot().FirstOrDefault().Descendants().Where(x => x.Id == Convert.ToInt32(nodeId) && x.IsVisible()).FirstOrDefault();
            if (OfficesNode != null)
            {
                NumberOfValues = OfficesNode.Children().Count().ToString();

                foreach (var office in OfficesNode.Children())
                {
                    var OfficesModel = new OfficesModel();
                    officeFlag = office.GetPropertyValue<string>("officeFlagImage");
                    officeName = office.GetPropertyValue<string>("officeName");
                    officeAddressName = office.GetPropertyValue<string>("officeAddressName");
                    officeAddressLine1 = office.GetPropertyValue<string>("officeaddressLine1");
                    officeAddressLine2 = office.GetPropertyValue<string>("officeAddressLine2");
                    officeAddressLine3 = office.GetPropertyValue<string>("officeAddressLine3");
                    officeAddressLine4 = office.GetPropertyValue<string>("officeAddressLine4");
                    officeTown = office.GetPropertyValue<string>("officeTown");
                    officeCounty = office.GetPropertyValue<string>("officeCountry");
                    officePostcode = office.GetPropertyValue<string>("officePostCode");
                    officePhone = office.GetPropertyValue<string>("officePhone");
                    extraPhone = office.GetPropertyValue<string>("extraPhone");
                    officeEmail = office.GetPropertyValue<string>("officeEmail");
                    officeWebsite = office.GetPropertyValue<string>("officeWebsite");
                    officeCountryCode = office.GetPropertyValue<string>("officeCountryCode");
                    RegisteredAddressLine1 = office.GetPropertyValue<string>("registeredAddressLine1");
                    RegisteredAddressLine2 = office.GetPropertyValue<string>("registeredAddressLine2");
                    RegisteredAddressLine3 = office.GetPropertyValue<string>("registeredAddressLine3");
                    RegisteredTown = office.GetPropertyValue<string>("registeredTown");
                    RegisteredPostcode = office.GetPropertyValue<string>("registeredPostcode");
                    RegisteredPhone = office.GetPropertyValue<string>("registeredPhone");
                    orContactUs = office.GetPropertyValue<string>("orContactUs");
                    orPressOne = office.GetPropertyValue<string>("orPressOne");
                    findOutHow = office.GetPropertyValue<string>("findOutHow");

                    if (officeName != null && officeAddressName != null)
                    {
                        OfficesModel.officeFlag = officeFlag;
                        OfficesModel.officeName = officeName;
                        OfficesModel.officeAddressName  = officeAddressName;
                        OfficesModel.officeAddressLine1 = officeAddressLine1;
                        OfficesModel.officeAddressLine2 = officeAddressLine2;
                        OfficesModel.officeAddressLine3 = officeAddressLine3;
                        OfficesModel.officeAddressLine4 = officeAddressLine4;
                        OfficesModel.officeCounty = officeCounty;
                        OfficesModel.officePostcode = officePostcode;
                        OfficesModel.officePhone = officePhone;
                        OfficesModel.officeEmail = officeEmail;
                        OfficesModel.officeWebsite = officeWebsite;
                        OfficesModel.officeCountryCode = officeCountryCode;
                        OfficesModel.RegisteredAddressLine1 = RegisteredAddressLine1;
                        OfficesModel.RegisteredAddressLine2 = RegisteredAddressLine2;
                        OfficesModel.RegisteredAddressLine3 = RegisteredAddressLine3;
                        OfficesModel.RegisteredTown = RegisteredTown;
                        OfficesModel.RegisteredPostcode = RegisteredPostcode;
                        OfficesModel.RegisteredPhone = RegisteredPhone;
                        OfficesModel.orContactUs = orContactUs;
                        OfficesModel.orPressOne = orPressOne;
                        OfficesModel.findOutHow = findOutHow;

                        OfficesList.Add(OfficesModel);

                    }
                    
                }
            }
            return OfficesList;
        }
        [ChildActionOnly]
        public ActionResult  GetSocialIcons()
        {
            return PartialView("socialOffices");
        }
    }
}

Umbraco Redesign/Views/Partials/OfficesForContact.cshtml
@model List<Umbraco_Redesign.Models.OfficesModel>
@*@using Umbraco.Web.Models
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage*@
@{
    var offices = Model;
}

<div class="col-xs-12 col-md-12 container">
    @{
        object officeFlag;
        var officeName = String.Empty;
        var officeAddressName = String.Empty;
        var officeAddressLine1 = String.Empty;
        var officeAddressLine2 = String.Empty;
        var officeAddressLine3 = String.Empty;
        var officeAddressLine4 = String.Empty;
        var officeTown = String.Empty;
        var officeCounty = String.Empty;
        var officePostcode = String.Empty;
        var officePhone = String.Empty;
        var officeEmail = String.Empty;
        var extraHeading = String.Empty;
        var extraHeadingContent = String.Empty;
        var mobilePhone = String.Empty;
        var extraPhone = String.Empty;
        var extraEmail = String.Empty;
        var officeWebsite = String.Empty;
        var officeCountryCode = String.Empty;
        var RegisteredAddressLine1 = String.Empty;
        var RegisteredAddressLine2 = String.Empty;
        var RegisteredAddressLine3 = String.Empty;
        var RegisteredTown = String.Empty;
        var RegisteredPostcode = String.Empty;
        var RegisteredPhone = String.Empty;
        var orContactUs = String.Empty;
        var orPressOne = String.Empty;
        var findOutHow = String.Empty;
        var officeFlagUrl = String.Empty;
        var showInOfficeMenu = String.Empty;
        var shopperSupportTeam = String.Empty;

        int itemCount = 0;
        var hasRegisteredOffice = false;
        var isUk = false;
        var isMainOffice = false;
       <ul class="social-button-offices">
        @Html.Action("GetSocialIcons", "Offices")
        </ul>
        @*<ul class="social-icons-list" style="display: inline; position: absolute; top: 5px; right: 250px;">
            <li style="display: inline; margin-right:15px;"><i class="fa fa-facebook-official fa-5x" aria-hidden="true" style="color:#3a559f"></i></li>
            <li style="display: inline; margin-right:15px;"><i class="fa fa-twitter fa-5x" aria-hidden="true" style="color:#6caddf"></i></li>
            <li style="display: inline; margin-right:15px;"><i class="fa fa-linkedin-square fa-5x" aria-hidden="true" style="color:#0097d3"></i></li>
            <li style="display: inline; margin-right:15px;"><i class="fa fa-instagram fa-5x" aria-hidden="true" style="color:#fff"></i></li>
            <li style="display: inline; margin-right:15px;"><i class="fa fa-youtube fa-5x" aria-hidden="true" style="color:#fff"></i></li>
        </ul>*@
        if (offices != null)
        {
        foreach (var office in offices)
        {
        officeFlag = office.officeFlag;
        officeFlagUrl = office.officeFlagUrl;
        officeName = office.officeName;
        officeAddressName = office.officeAddressName;
        officeAddressLine1 = office.officeAddressLine1;
        officeAddressLine2 = office.officeAddressLine2;
        officeAddressLine3 = office.officeAddressLine3;
        officeAddressLine4 = office.officeAddressLine4;
        officeTown = office.officeTown;
        officeCounty = office.officeCounty;
        officePostcode = office.officePostcode;
        officePhone = office.officePhone;
        officeEmail = office.officeEmail;
        extraHeading = office.extraHeading;
        extraHeadingContent = office.extraHeadingContent;
        mobilePhone = office.mobilePhone;
        extraPhone = office.extraPhone;
        extraEmail = office.extraEmail;
        officeWebsite = office.officeWebsite;
        officeCountryCode = office.officeCountryCode;
        RegisteredAddressLine1 = office.RegisteredAddressLine1;
        RegisteredAddressLine2 = office.RegisteredAddressLine2;
        RegisteredAddressLine3 = office.RegisteredAddressLine3;
        RegisteredTown = office.RegisteredTown;
        RegisteredPostcode = office.RegisteredPostcode;
        RegisteredPhone = office.RegisteredPhone;
        orContactUs = office.orContactUs;
        orPressOne = office.orPressOne;
        findOutHow = office.findOutHow;
        showInOfficeMenu = office.showInOfficeMenu;
        shopperSupportTeam = office.shopperSupportTeam;
        if (officeCountryCode.Contains("uk"))
        {

        isUk = true;
        }
        else
        {
        isUk = false;
        }
        if (showInOfficeMenu.Contains("Show"))
        {
       <div class="col-xs-4 col-md-4 float-left" style="display:block;vertical-align:top;margin: 20px auto;">
           <div class="col-xs-8 col-md-8">
               <div class="row">
                   @if (@officeFlagUrl != null && @officeName != "Registered Address")
                   {

                       <div class="col-xs-3" style="margin-right: 10px;">
                           <img src="@officeFlagUrl" alt="officeFlag" />
                       </div>

                   }
                   @if (@officeName != null && @officeName != "Registered Address")
                   {
                       <div class="col-xs-3">
                           @officeName
                       </div>
                   }
                   else
                   {
                       <p id="ptag1" style="text-align:left;margin-top:15px;font-size:20px;">@officeName</p>
                   }
               </div>

               @if (@officeAddressName != null)
               {
                   <p id="ptag1" style="text-align:left;margin-top:15px;font-size:20px;">@officeAddressName</p>
               }
               @if (@officeAddressLine1 != null)
               {
                   <p id="ptag2" style="text-align:left;font-size:17px;">@officeAddressLine1</p>
               }
               @if (@officeAddressLine2 != null)
               {
                   <p id="ptag3" style="text-align:left;font-size:17px;">@officeAddressLine2</p>
               }
               @if (@officeAddressLine3 != null)
               {
                   <p id="ptag3" style="text-align:left;font-size:17px;">@officeAddressLine3</p>
               }
               @if (@officeTown != null)
               {
                   <p id="ptag4" style="text-align:left;font-size:17px;">@officeTown</p>
               }
               @if (@officeCounty != null)
               {
                   <p id="ptag4" style="text-align:left;font-size:17px;">@officeCounty</p>
               }
               @if (@officePostcode != "")
               {
                   <p id="ptag5" style="text-align:left;font-size:17px;">@officePostcode</p>
               }
               @if (@officePhone != null)
               {
                   <p id="ptag6" style="text-align:left;margin-top:20px;font-size:17px;"><strong>Phone: </strong>@officePhone</p>
               }
               @if (@officeEmail != "")
               {
                   <p id="ptag7" style="text-align:left;margin-top:20px;font-size:17px;width:200px; white-space:initial;"> <strong>Email: </strong> @officeEmail</p>
               }
               @if (@shopperSupportTeam != "")
               {
                   <p id="ptag8" style="text-align:left;margin-top:20px;font-size:17px; width:200px; white-space:initial;"><strong>Shopper Support Team: </strong>@shopperSupportTeam</p>
               }
               @if (@extraPhone != "")
               {
                   <p id="ptag9" style="text-align:left;margin-top:20px;font-size:17px;"><strong>Phone: </strong>@extraPhone</p>
               }
               @if (@extraEmail != "")
               {
                   <p id="ptag10" style="text-align:left;margin-top:20px;font-size:17px;"><strong>Email: </strong>@extraEmail</p>
               }
           </div>
       </div>
      
    }
}
</div>

Umbraco Redesign/Views/Partials/Sections - Copy.cshtml
@using Umbraco.Web.Models
@inherits Umbraco.Web.Mvc.UmbracoViewPage<IPublishedContent>

@{
    Layout = null;
}



@{
    var pageId = Convert.ToInt32(TempData["pageId"]);



    IPublishedContent page = null;

    if(pageId == 0)
    {
        page = UmbracoContext.Current.PublishedContentRequest.PublishedContent;
    }
    else
    {
        page = Umbraco.TypedContent(pageId);
    }

    //var page =    .Convert.ToInt32(TempData["sectionId"]);
    //var page = UmbracoContext.Current.PublishedContentRequest.PublishedContent;
    IEnumerable<IPublishedContent> sections = null;


    if (page != null)
    {
        if (page.DocumentTypeAlias == "homePage")
        {
            sections = page.Descendants().Where(x => x.IsVisible() && x.DocumentTypeAlias.ToString().Contains("section") && Convert.ToBoolean(x.GetPropertyValue("mSLShowOnHomePage")) == true).OrderBy(x => x.GetPropertyValue<int>("mSLSectionOrderNumber"));
        }
        else
        {
            sections = page.Descendants().Where(x => x.IsVisible() && x.DocumentTypeAlias.ToString().Contains("section")).OrderBy(x => x.GetPropertyValue<int>("mSLSectionOrderNumber"));
        }





        @*<div class="sectionContainer container">*@

        if (sections.Count() > 0)
        {
            int sectionCount = 0;


            foreach (var mslSection in sections)
            {
                var sectionId = "section" + mslSection.Id;
                var hasBackground = Convert.ToBoolean(mslSection.GetPropertyValue("mSLHasBackgroundColor"));
                string backgroundColor = "none";
                string textColor = String.Empty;
                string classes = String.Empty;

                if (Convert.ToBoolean(mslSection.GetPropertyValue("mSLShowOnHomePage")) == true && sectionCount == 0)
                {
                    classes = "sectionContentWrapper onlyHomePageSection home-page text-focus-in";
                }
                else
                {
                    classes = "sectionContentWrapper fadeOut";
                }

                if (hasBackground)
                {
                    textColor = "#000";

                    if (mslSection.GetPropertyValue("mSLSectionBackgroundColor") != null)
                    {
                        backgroundColor = "#" + mslSection.GetPropertyValue<string>("mSLSectionBackgroundColor");
                    }
                }
                else
                {
                    textColor = "#fff";
                }


                <div class="@classes">

                    <div class="sectionHeading col-md-12">
                        <h1>@mslSection.Name</h1>
                    </div>

                    <div id="@sectionId" class="section contentWrapper" style="background-color:@backgroundColor;color:@textColor;">
                        @mslSection.GetGridHtml(Html, "sectionLayout")
                    </div>

                </div>
                sectionCount = sectionCount + 1;
            }
        }
        else
        {

            var hasBackground = Convert.ToBoolean(page.GetPropertyValue("mSLHasBackgroundColor"));
            var backgroundColor = "#" + page.GetPropertyValue("mSLSectionBackgroundColor");
            var textColor = String.Empty;

            if (hasBackground)
            {
                textColor = "#000";
            }
            else
            {
                textColor = "#fff";
            }

            <div class="container">

                <div class="sectionContentWrapper onlyHomePageSection">
                    <h1>@page.Name</h1>
                    <div class="section contentWrapper" style="color:@textColor;background-color:@backgroundColor">


                        @{

                            if (page.DocumentTypeAlias == "singlePageWithLayout")
                            {
                                if (page.GetProperty("mslSectionLayout") != null)
                                {
                                    @page.GetGridHtml(Html, "mslSectionLayout");
                                }
                            }
                            else
                            {
                                <h2 style="color:#fff;">Display Content</h2>
                            }
                        }

                    </div>
                </div>
            </div>

        }

        @*</div>*@
    }



}

Umbraco Redesign/Views/Partials/associations.cshtml
@using Umbraco.Web.Models
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

@{
    IPublishedContent associationsNode = null;
    IEnumerable<IPublishedContent> associations = null;

    associationsNode = Umbraco.TypedContentAtRoot().SelectMany(x => x.DescendantsOrSelf().Where(c => c.DocumentTypeAlias == "associations")).FirstOrDefault();

    if (associationsNode != null)
    {
        associations = associationsNode.Children();
    }
}

@foreach (IPublishedContent association in associations)
    {
        var associationLogo = Umbraco.TypedMedia(association.GetPropertyValue("associationLogo").ToString());
        string logoUrl = String.Empty;

        if (associationLogo != null)
        {
            logoUrl = associationLogo.Url;
        }

        var associationsProp = association.GetProperty("associationLink").DataValue;
        var jsonText = (Newtonsoft.Json.Linq.JArray)Newtonsoft.Json.JsonConvert.DeserializeObject(associationsProp.ToString());
        var target = jsonText[0]["target"];
        var associationLink = jsonText[0]["url"];
        var associationLinkAltText = association.GetPropertyValue("associationLinkAltText");

    <a href="@associationLink" target="@target" class="logos-in-navbar">
        <img src="@logoUrl" alt="@associationLinkAltText">
    </a>
}

Umbraco Redesign/Views/Partials/mainbody.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

Umbraco Redesign/Views/Partials/success.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

<h1>Thank You For Your Enquiry</h1>
<p>We will get back to you shortly</p>